<?php
/**
 * Created by PHPro
 *
 * @package      DPD
 * @subpackage   Shipping
 * @category     Checkout
 * @author       PHPro (info@phpro.be)
 */
/**
 * Import the api with or without key in header.
 */
?>
<?php if (Mage::getStoreConfig('carriers/dpdparcelshops/google_maps_api') != ""): ?>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo Mage::getStoreConfig('carriers/dpdparcelshops/google_maps_api') ?>&sensor=false&v=3.13"
        type="text/javascript"></script>
<?php else: ?>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&v=3.13" type="text/javascript"></script>
<?php endif; ?>
