<?php
/**
 * Created by PHPro
 *
 * @package      DPD
 * @subpackage   Shipping
 * @category     Checkout
 * @author       PHPro (info@phpro.be)
 */
/**
 * Set ordertracking link in my account.
 */
?>
<?php
$orderId = Mage::registry('current_shipping_info')->getOrderId();
if(!$orderId){
    $orderId = Mage::getModel('sales/order_shipment')->load(Mage::registry('current_shipping_info')->getShipId())->getOrderId();
}
$order = Mage::getModel('sales/order')->load($orderId);
$arrayToReplace = array("$1", "$2", "$3");
$localeExploded = explode('_',Mage::app()->getLocale()->getLocaleCode());
$replaceArray = array($order->getIncrementId(),$localeExploded[0],Mage::getStoreConfig('shipping/dpdclassic/userid'));
$url = "https://tracking.dpd.de/parcelstatus?locale=en_BE&query=$1";//"http://tracking.dpd.de/cgi-bin/delistrack?typ=5&lang=$2&pknr=$1&var=$3";
$parsedUrl = str_replace($arrayToReplace,$replaceArray,$url);
?>
<?php if(strpos(serialize($this->getTrackingInfo()), 'DPD' ) !== FALSE): ?>
<div class="order-tracking">
    <a style="position: absolute;top: <?php echo (Mage::helper('dpd')->isMageEnterprise() ? ' 85' : ' 65' )?>px" href="<?php echo $parsedUrl ?>" alt="ordertrackingUrl" target="_blank"><?php echo Mage::helper('dpd')->__('Track this order') ?></a>
</div>
<?php endif; ?>
